[package]
name = "gptchat_draws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"
pixels = "0.10"
winit = "0.27"
winit_input_helper = "0.13"